server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:dev
#配置数据库驱动
    driver-class-name: org.h2.Driver
#配置数据库用户名
    username: sa
#配置数据库密码
    password:
#配置能远程访问
  h2:
    console:
      settings:
        web-allow-others: true
regCenter:
  serverList: localhost:2181
  namespace: demo
simpleJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 5
  shardingItemParameters: 1=A,2=B,3=C,4=D,5=E